# Generated by Django 5.0.6 on 2024-07-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qty',
            new_name='product_qty',
        ),
    ]
